### ISSUE TITLE
"MVPリリース"レビュー依頼

### ISSUE THREAD

**Issue by komayuu** [komayuu/DrinkCollection#25]
## 各種情報
サービスの概要とMVPで検証する事柄：投稿機能で他のユーザーのおすすめのお酒が見れたり、自分のおすすめのお酒を投稿することができる。ユーザー登録をすることで、登録ユーザーの投稿一覧を閲覧できる。ユーザーは自分の投稿を編集・削除することができる。
サービス名：DrinkCollection
サービスURL：https://drinkcollection.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 投稿閲覧機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 記事投稿機能
- [x] 記事編集機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください。

### 追加した機能
- 記事削除機能
- 投稿詳細画面の作成
- フラッシュメッセージの設定
### MVPリリース時点で作らなくなった機能
- 記事投稿・編集機能（画像挿入部分）
- 記事投稿・編集機能（カテゴリ選択）

## サービスイメージがわかるようなスクリーンショット等
[トップページ(ログイン時)](https://i.gyazo.com/440d7dd816ac47e2e8ec31e930c05769.jpg)
[投稿閲覧機能(投稿一覧)](https://i.gyazo.com/e9229ee9a8855dcba136379948ad1774.png)
投稿一覧画面を表示
[ユーザー登録機能](https://i.gyazo.com/3739c72771854ecca5ba836851549949.png)
新規登録画面を表示
[ログイン機能](https://i.gyazo.com/61f13eee21b23f4783a76697b6a6983b.png)
ログイン画面を表示
[記事投稿機能](https://i.gyazo.com/f1852d766ad4fcc82ee5ed9a8d97bb26.png)
投稿作成画面を表示
[記事編集機能](https://i.gyazo.com/1e7d281ac521510d35a86c0e3b999f2d.png)
投稿編集画面を表示

**Comment by komayuu** [comment]
お疲れ様です。

レビューいただきありがとうございます。
こちら説明させていただます。
操作の動線は合っているのですが、「ヘッダーの範囲」と「title、編集（鉛筆）アイコン、削除（ゴミ箱）アイコン」がほぼ重なっているため起こっている現象になります。
トップページのデザインを優先して作った時にヘッダーを透過させ、z-indexで重ねているのが原因です。
※竹中講師のキャプチャ映像でも、一瞬マウスの矢印から指のマークに変わっているのが見受けられます。

下記、記事の編集機能と削除機能のキャプチャ映像になります。
- 記事の編集機能
[![Image from Gyazo](https://i.gyazo.com/b316d11f3291e73e2c0875745bd2db7c.gif)](https://gyazo.com/b316d11f3291e73e2c0875745bd2db7c)

- 記事の削除機能
[![Image from Gyazo](https://i.gyazo.com/a69721afe8013130a1bed51a9be4c7fd.gif)](https://gyazo.com/a69721afe8013130a1bed51a9be4c7fd)

お手数おかけしますが、２段目以降の記事で、いま一度編集・削除機能をご確認いただけないでしょうか。
ご確認のほど、よろしくお願い申し上げます。

**Comment by ippei-shimizu** [comment]
1列目の投稿の詳細にアクセスしずらく、ユーザー体験がかなり下がってしまうため、ヘッダーと一覧のコンテンツ要素に間に余白をいれて、1列目の投稿もクリックができるようにしてください。

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/77840970cac14a15f75a4111a62436b6.png)](https://startup-technology.gyazo.com/77840970cac14a15f75a4111a62436b6)

**Comment by komayuu** [comment]
お疲れ様です。

機能を優先したため、CSSを後回しにしていました。
アプリを使用できるようにするため`<div class="pt-16"></div>`を追記し、１列目の投稿へのアクセスしづらさを解消しました。
MVPリリース後、デザインを変更する際に再度調整いたします。
[![Image from Gyazo](https://i.gyazo.com/654cfb2e00c4a20b73a68270b02d8f6b.png)](https://gyazo.com/654cfb2e00c4a20b73a68270b02d8f6b)

**Comment by busitora** [comment]
1.エラーメッセージですが、視認性にかけますので、ヘッダーの下に出すようにしてください。
<img width="1127" alt="スクリーンショット 0006-12-23 19 57 54" src="https://github.com/user-attachments/assets/9b20ade0-2124-446b-9309-843142a59369" />

2. https://drinkcollection.onrender.com/posts# 細かいですが、画像をクリックした際も詳細ページにアクセスできるとなおいいですね。
3. https://drinkcollection.onrender.com/posts/11111 のようなURLにアクセスした際にエラーになりますので、対応お願いします。

**Comment by komayuu** [comment]
レビューありがとうございます。

１．申し訳ありませんが、本リリースにてデザイン変更時に調整いたします。
２．こちら対応しました。
[![Image from Gyazo](https://i.gyazo.com/0f3d5e1645766d599cc86334b9cec4ce.gif)](https://gyazo.com/0f3d5e1645766d599cc86334b9cec4ce)

３．下記ご確認お願いいたします。
[![Image from Gyazo](https://i.gyazo.com/183ef38238869ff8e99e9fb9f9abd4aa.gif)](https://gyazo.com/183ef38238869ff8e99e9fb9f9abd4aa)

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
LGTMです！

**Comment by komayuu** [comment]
お疲れ様です。
ご確認いただきありがとうございます。
