### ISSUE TITLE
issueベースの開発

### ISSUE THREAD

**Issue by komayuu** [komayuu/DrinkCollection#26]
お世話になっております。
issueを作成いたしました。
ご確認のほど、よろしくお願い申し上げます。

## Webアプリの概要
本サービスは、お酒好きの方や興味のある方が楽しめるアプリケーションです。
ユーザー登録をすることで、お気に入りのお酒を投稿したり、他のユーザーがおすすめするお酒をチェックすることができます。
アプリ内の豊富なデータべースから、さまざまなお酒を調べることができます。また、検索機能を使えば、カクテルの名前から作り方を調べたり、カテゴリ別に絞り込んだりできます。ノンアルコールカクテルのリストもあり、お酒が苦手な方も楽しめます。
ログイン後は、ユーザーの投稿記事やブックマークしたお酒をマイページで確認できます。お気に入りのお酒をブックマークすることで、後で見返す時も便利です。
お酒好きの方はもちろん、雰囲気を楽しみたい方にも、新しいお酒との出会いを提供するアプリとなっています。

## 1週間辺りの開発に向けられる時間
- 1週間あたり：25時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

## ProjectsのURL
https://github.com/users/komayuu/projects/1/views/1
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。

## MVPリリースまで
- [ ] Rails new
- [ ] Renderにデプロイ
- [ ] トップページの作成
- [ ] ヘッダーの作成
- [ ] フッターの作成
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] 投稿一覧機能
- [ ] 記事投稿機能
- [ ] 記事詳細機能
- [ ] 記事編集機能
- [ ] 記事削除機能
- [ ] フラッシュメッセージの設定

## MVP後（本リリース）
- [ ] 検索機能
- [ ] マルチ検索 or オートコンプリート検索機能
- [ ] SNSログイン（Google認証）
- [ ] SNS共有機能（X共有機能）
- [ ] マイページ機能
- [ ] お酒のカテゴリページ作成
- [ ] お酒の詳細ページ作成
- [ ] お酒のデータベース作成
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせフォーム機能
- [ ] パスワードリセット機能
- [ ] パスワード更新
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] ファビコン
- [ ] 独自ドメイン
- [ ] レスポンシブ対応
- [ ] OGP（静的）

## MVPレビュー依頼予定日
予定日：2024年 12月 23日

**Comment by beppumasaki** [comment]
概ね良いかと思います。LGTMです。

**Comment by komayuu** [comment]
ご確認いただきありがとうございます！
